// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.14.0
// source: mathexpr.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MathExpression_GetVariablesList_FullMethodName = "/mathexpression.MathExpression/getVariablesList"
	MathExpression_GetDataPoints_FullMethodName    = "/mathexpression.MathExpression/getDataPoints"
)

// MathExpressionClient is the client API for MathExpression service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MathExpressionClient interface {
	GetVariablesList(ctx context.Context, in *ExprRequest, opts ...grpc.CallOption) (*VariablesListReply, error)
	GetDataPoints(ctx context.Context, in *DataPointsRequest, opts ...grpc.CallOption) (*DataPointsReply, error)
}

type mathExpressionClient struct {
	cc grpc.ClientConnInterface
}

func NewMathExpressionClient(cc grpc.ClientConnInterface) MathExpressionClient {
	return &mathExpressionClient{cc}
}

func (c *mathExpressionClient) GetVariablesList(ctx context.Context, in *ExprRequest, opts ...grpc.CallOption) (*VariablesListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariablesListReply)
	err := c.cc.Invoke(ctx, MathExpression_GetVariablesList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mathExpressionClient) GetDataPoints(ctx context.Context, in *DataPointsRequest, opts ...grpc.CallOption) (*DataPointsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataPointsReply)
	err := c.cc.Invoke(ctx, MathExpression_GetDataPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathExpressionServer is the server API for MathExpression service.
// All implementations must embed UnimplementedMathExpressionServer
// for forward compatibility.
type MathExpressionServer interface {
	GetVariablesList(context.Context, *ExprRequest) (*VariablesListReply, error)
	GetDataPoints(context.Context, *DataPointsRequest) (*DataPointsReply, error)
	mustEmbedUnimplementedMathExpressionServer()
}

// UnimplementedMathExpressionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMathExpressionServer struct{}

func (UnimplementedMathExpressionServer) GetVariablesList(context.Context, *ExprRequest) (*VariablesListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVariablesList not implemented")
}
func (UnimplementedMathExpressionServer) GetDataPoints(context.Context, *DataPointsRequest) (*DataPointsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataPoints not implemented")
}
func (UnimplementedMathExpressionServer) mustEmbedUnimplementedMathExpressionServer() {}
func (UnimplementedMathExpressionServer) testEmbeddedByValue()                        {}

// UnsafeMathExpressionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MathExpressionServer will
// result in compilation errors.
type UnsafeMathExpressionServer interface {
	mustEmbedUnimplementedMathExpressionServer()
}

func RegisterMathExpressionServer(s grpc.ServiceRegistrar, srv MathExpressionServer) {
	// If the following call pancis, it indicates UnimplementedMathExpressionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MathExpression_ServiceDesc, srv)
}

func _MathExpression_GetVariablesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExprRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathExpressionServer).GetVariablesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathExpression_GetVariablesList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathExpressionServer).GetVariablesList(ctx, req.(*ExprRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MathExpression_GetDataPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathExpressionServer).GetDataPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MathExpression_GetDataPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathExpressionServer).GetDataPoints(ctx, req.(*DataPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MathExpression_ServiceDesc is the grpc.ServiceDesc for MathExpression service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MathExpression_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mathexpression.MathExpression",
	HandlerType: (*MathExpressionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getVariablesList",
			Handler:    _MathExpression_GetVariablesList_Handler,
		},
		{
			MethodName: "getDataPoints",
			Handler:    _MathExpression_GetDataPoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mathexpr.proto",
}
